ace_api/urls.py
from django.urls import path
from ace_api.views import AceList

urlpatterns = [
    path('index', AceList.as_view(), name='index'),
]

ace_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/', include('ace_api.urls')),
]

ace_api/models.py
from django.db import models

# Create your models here.


class Ace(models.Model):
    nome = models.CharField(max_length=255)
    matricula = models.CharField(max_length=6)
    zona = models.IntegerField()
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.nome


def is_prime(num):

    if num > 1:

       for i in range(2, num):
           if (num % i) == 0:
               return False
       else:
           return True

    else:
       return False

ace_api/forms.py
from django import forms
from .models import  Indice


class IndiceForm(forms.ModelForm):

    class Meta:
        model = Indice
        fields = '__all__'

ace_api/views.py
from django.shortcuts import render
from .models import Ace
from django.views.generic.list import ListView


# Create your views here.


class AceList(ListView):
    model = Ace
    fields = '__all__'
    template_name = 'index.html'

templates/base.html
<!DOCTYPE html>
<html>

<head>
    <title>Api Ace</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
    <meta name="google" content="notranslate" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" />
</head>

<body>
    <style>
        body {
            font-family: "Roboto", sans-serif;
            font-size: 17px;
            background-color: #fdfdfd;
        }

        .shadow {
            box-shadow: 0 4px 2px -2px rgba(0, 0, 0, 0.1);
        }

        .btn-danger {
            color: #fff;
            background-color: #f00000;
            border-color: #dc281e;
        }

        .masthead {
            background: #3398E1;
            height: auto;
            padding-bottom: 15px;
            box-shadow: 0 16px 48px #E3E7EB;
            padding-top: 10px;
        }
    </style>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="mainNav">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'index' %}">Api Ace</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item text-black">
                        <a class="nav-link text-black font-weight-bold" href="#">About</a>
                    </li>
                    <li class="nav-item text-black">
                        <a class="nav-link text-black font-weight-bold" href="#">Policy</a>
                    </li>
                    <li class="nav-item text-black">
                        <a class="nav-link text-black font-weight-bold" href="#">Contact</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    {% block content %}
    <!-- Content Goes here -->
    {% endblock content %}
    <!-- Footer -->
    <footer class="py-3 bg-grey">
        <p class="m-0 text-dark text-center ">Copyright &copy; Ace Api</p>
    </footer>
</body>

</html>

templates/index.html
{% extends "base.html" %}

{% block content %}
<style>
    body {
        font-family: "Roboto", sans-serif;
        font-size: 18px;
        background-color: #fdfdfd;
    }

    .head_text {
        color: white;
    }

    .card {
        box-shadow: 0 16px 48px #E3E7EB;
    }
</style>

<header class="masthead">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">
                   
                </div>
            </div>
        </div>
    </div>
</header>
<div class="container">
    <div>


    </div>
    <div>
        <h1>Lista de Ace</h1>
    </div>
    <table class="table">
        <thead class="thead-dark">
            <tr>

                <th scope="col">Nome</th>
                <th scope="col">Matricula</th>
                <th scope="col">Zona</th>
            </tr>
        </thead>
        <tbody>
            {% for a in ace_list %}
            <tr>
                <th scope="row">{{ a.nome }}</th>
                <td>{{ a.matricula}}</td>
                <td>{{ a.zona}}</td>

                <td>
                    <a type="submit" class="btn btn-warning" href="" method="POST">Editar</a>
                    <a type="submit" class="btn btn-danger" href="" method="POST">Exluir</a>
                </td>
            </tr>
            <!-- If object_list is empty -->
            {% empty %}
            <h1>No objects Find</h1>

            {% endfor %}
        </tbody>
    </table>

</div>
{%endblock%}

templates/indice.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container">
    {% if user.is_anonymous %}
    <h1>Você não está logado</h1>
    {% else %}
    <h1>
        Olá {{ user.username }}. Este é o Ciclo {{ciclo}} <a href="{% url 'mapa' ciclo  %}" class="btn btn-success">Mapa de calor &rarr;</a>
    </h1>
    
    {% endif %}
    <table class="table">
        <thead class="thead-dark">
            <tr>

                <th scope="col">Id</th>
                <th scope="col">Bairro</th>
                <th scope="col">Indice</th>

            </tr>
        </thead>
        <tbody>
            {% for i in indices %}
            <tr>

                <td>{{ i.id}}</td>
                <td>{{ i.bairro_nome}}</td>
                <td>{{ i.indice_bairro }}</td>


                <td>
                    <a type="submit" class="btn btn-warning" href=""
                        method="POST">Editar</a>
                </td>
            </tr>
            {% empty %}
            <h1>No objects Find</h1>
            {% endfor %}

        </tbody>
    </table>
    {% if user.is_anonymous %}

    {% else %}
    <div class="row">
        <div class="col-md-6 offset-md-2">
            <div class="card auth-card">
                <div class="card-body">
                    <h1>Adicionar Índice</h1>
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ indice_form | crispy }}

                        <br>
                        <button class="btn btn-primary" type="submit">Salvar</button>
                    </form>
                </div>
            </div>


        </div>

    </div>
    {% endif %}


</div>

{% endblock content %}

templates/indice_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Editar Indice{% endblock %}

{% block content %}
<br>
<div class="row">
    <div class="col-md-4 offset-md-4">
        <div class="card auth-card">
            <div class="card-body">
                <h1>Editar Indice</h1>
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ indice_form | crispy }}

                    <br>
                    <button class="btn btn-primary" type="submit" href="{% url {{resquest.path}}%}">Salvar</button>
                </form>
            </div>
        </div>


    </div>

</div>

{% endblock %}

templates/mapcaico.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>Mapa de calor do {{ciclo}}º LIRA</h1>
    
    {{ map|safe }}

</div>

{% endblock %}